@AS2425.4G.Prof.IoTForHealtBE_HostAddress = https://localhost:7242
@AS2425._4G.Prof.IoTForHealtBE_HostAddress = http://localhost:5195

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJuYW1lLnN1cm5hbWUiLCJqdGkiOiI5ZTZhODgwZi04NzFkLTQ2YjYtOTNhZS02ZjExMTU5ZWM1OWUiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNzQwNTY0NzcxLCJpc3MiOiJ5b3VyZG9tYWluLmNvbSIsImF1ZCI6InlvdXJkb21haW4uY29tIn0.keQsYhYT72mJjI6r7xZoDzm4At4BvJ1ptsIpbmWP6lY


GET {{AS2425.4G.Prof.IoTForHealtBE_HostAddress}}/api/patients

###

POST {{AS2425.4G.Prof.IoTForHealtBE_HostAddress}}/api/login
Content-Type: application/json

{
    "role": "PATIENT",
    "username": "name.surname",
    "password": "password1"
}

###


GET {{AS2425.4G.Prof.IoTForHealtBE_HostAddress}}/api/patients
Authorization: Bearer {{token}}
###

@id=1
GET {{AS2425.4G.Prof.IoTForHealtBE_HostAddress}}/api/patients/{{id}}
Authorization: Bearer {{token}}
###

